extends Node
## Autoload: loads the card catalog from res://database/cards.json at startup
## and provides typed lookups. Card data is immutable — adding dinosaurs only
## requires editing the JSON (regenerated by tools/jurassic_scraper.py).

const CARDS_PATH := "res://database/cards.json"

var dinos: Array[DinoCardData] = []
var trainers: Array[TrainerCardData] = []
var fields: Array[FieldCardData] = []
var instincts: Array[InstinctCardData] = []

var _by_id: Dictionary = {}


func _ready() -> void:
	_load_catalog()


## Every card in the pool, in a stable order.
func all_cards() -> Array[CardData]:
	var cards: Array[CardData] = []
	cards.append_array(dinos)
	cards.append_array(trainers)
	cards.append_array(fields)
	cards.append_array(instincts)
	return cards


func get_card(card_id: String) -> CardData:
	if not _by_id.has(card_id):
		push_error("GameData: unknown card id '%s'" % card_id)
		return null
	return _by_id[card_id]


func has_card(card_id: String) -> bool:
	return _by_id.has(card_id)


func _load_catalog() -> void:
	var file := FileAccess.open(CARDS_PATH, FileAccess.READ)
	if file == null:
		push_error("GameData: cannot open %s" % CARDS_PATH)
		return
	var parsed: Variant = JSON.parse_string(file.get_as_text())
	if typeof(parsed) != TYPE_DICTIONARY:
		push_error("GameData: %s is not a JSON object" % CARDS_PATH)
		return
	var catalog: Dictionary = parsed

	for entry: Dictionary in catalog.get("dinos", []):
		_register(DinoCardData.from_dict(entry), dinos)
	for entry: Dictionary in catalog.get("trainers", []):
		_register(TrainerCardData.from_dict(entry), trainers)
	for entry: Dictionary in catalog.get("fields", []):
		_register(FieldCardData.from_dict(entry), fields)
	for entry: Dictionary in catalog.get("instincts", []):
		_register(InstinctCardData.from_dict(entry), instincts)

	print("GameData: loaded %d cards (%d dinos, %d trainers, %d fields, %d instincts)" % [
		_by_id.size(), dinos.size(), trainers.size(), fields.size(), instincts.size(),
	])


func _register(card: CardData, into: Array) -> void:
	if card == null:
		return  # from_dict already reported the specific problem
	if _by_id.has(card.id):
		push_error("GameData: duplicate card id '%s'" % card.id)
		return
	_by_id[card.id] = card
	into.append(card)
